// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajoaegialqynjnnlhote.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqb2FlZ2lhbHF5bmpubmxob3RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3MTY5NzMsImV4cCI6MjA4NzI5Mjk3M30.pa4U7ig1H45Y_cS2Ka395UgyNgbzGMBj-45wgQsuSvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});